### Creating an Dataset and training an Artificial neural Network with Keras 

#### problem : 
#### Drug vaccination given b/w age 13 to 100 years.                                           
#### 1.people > 65  : observed some side effects  (given label=1)                                   
#### 2.people < 65  : no side effects       (given label=0)

#### Importing libraries

In [1]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

import numpy as np
from random import randint   
from sklearn.preprocessing import MinMaxScaler

Using TensorFlow backend.


In [2]:
train_sample = []    # list of diffrenert people contains age
train_label = []    # provide 0 or 1 for vaccination of side-effect

for i in range(1000):                   # takes range 1000 for sample & label both, total=2000
    younger_ages = randint(13,64)       # we randomly initialize age : range of young people b/w 13 to 64
    train_sample.append(younger_ages)
    train_label.append(0)               # providing label=0 , bcoz younger people have no side-effect
    
    older_ages = randint(65,100)         # similarly for older people, age b/w 65 to 100 
    train_sample.append(older_ages)      
    train_label.append(1)                # provide label=1 
    
# After running this, we created our dataset. 

In [3]:
# train_sample
# train_label

In [4]:
# We need to convert this dataset into numpy array , bcoz keras expect input as numpy array.

train_sample = np.array(train_sample)     
train_label = np.array(train_label)       

train_sample

array([64, 88, 47, ..., 89, 36, 75])

In [5]:
# Now scaling 'train_sample' numbers bcoz sometime there is much gap b/w them using MinMaxscaler()

scaler = MinMaxScaler(feature_range=(0,1))

scaler_train_sample = scaler.fit_transform(train_sample.reshape(-1,1))  # when we do scaling, reshape it into 2D for keras

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [6]:
scaler_train_sample

array([[0.5862069 ],
       [0.86206897],
       [0.3908046 ],
       ...,
       [0.87356322],
       [0.26436782],
       [0.71264368]])

##### Now create - Artificial Neural Network

In [7]:
# Now we have the data and also done scaling, 
# In this Sequential() basically creating feed forward Neural Network

# Dense( creating 2 hidden layers) 
# In 1st hidden layer (16- no. of neurons, input_dim is 1D array, 
# activation func. used to transfrom input data into weight which we add through bias and 
# the summation of input feature & weight is actually transfrom 0 to 1) , 
# layer2-Dense( 32- no. of neurons and same..),
# layer3- Dense(2 outputs- 0,1) is for output layer

model = Sequential([Dense(16, input_dim=1,activation='relu'),Dense(32,activation='relu'),Dense(2,activation='softmax')])

model.summary()

Instructions for updating:
Colocations handled automatically by placer.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 16)                32        
_________________________________________________________________
dense_2 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


### Compile and fit the model

In [8]:
# 'Adam' optimizer related to gradient descent which adjust the weights throughout the Neural Network
# lr-learning rate (helps to learn the model in gradient descent manner such that weights get adjust in network)
# loss= 'sparse categorical crossentropy' - used where output is 2 type classifier 0 or 1.

model.compile(Adam(lr=0.001),loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [9]:
# 'batch size' used to provide inputs in batch not 1 by 1 so that transformation can quicly takes place 
# epochs- how many times you iterate through your input features(no. of epochs increase, accuracy also increases).

model.fit(train_sample, train_label, batch_size=10, epochs=10)   

Instructions for updating:
Use tf.cast instead.
Epoch 1/10
2000/2000 [==============================] - 1s 466us/step - loss: 0.8807 - acc: 0.5645
Epoch 2/10
2000/2000 [==============================] - 0s 138us/step - loss: 0.5073 - acc: 0.7675
Epoch 3/10
2000/2000 [==============================] - 0s 141us/step - loss: 0.4228 - acc: 0.8540
Epoch 4/10
2000/2000 [==============================] - 0s 156us/step - loss: 0.3607 - acc: 0.8795
Epoch 5/10
2000/2000 [==============================] - 0s 155us/step - loss: 0.3098 - acc: 0.8975
Epoch 6/10
2000/2000 [==============================] - 0s 133us/step - loss: 0.2655 - acc: 0.9225
Epoch 7/10
2000/2000 [==============================] - 0s 162us/step - loss: 0.2498 - acc: 0.9245
Epoch 8/10
2000/2000 [==============================] - 0s 131us/step - loss: 0.2194 - acc: 0.9320
Epoch 9/10
2000/2000 [==============================] - 0s 141us/step - loss: 0.2135 - acc: 0.9275
Epoch 10/10
2000/2000 [==============================] - 0s 1

#### after fitting the model predict -> test_sample , test_label

In [10]:
test_sample=[]
test_label=[]

for i in range(500):                     # taking range 500 for testing purpose
    younger_ages = randint(13,64)
    test_sample.append(younger_ages)
    test_label.append(0)     
    
    older_ages = randint(65,100)
    test_sample.append(older_ages)
    test_label.append(1)
    
test_sample = np.array(test_sample)
test_label = np.array(test_label)

In [11]:
# test_sample

In [12]:
test_sample_output = model.predict_classes(test_sample, batch_size=10)

In [13]:
# Next Create- Confusion matrix, it checks how actually your model is performed, 
# and see what is my true value (test_label) & what is predicted value (test_sample_output)

from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(test_label,test_sample_output)    # shows what no. of prediction is accurately done
acc = accuracy_score(test_label, test_sample_output)

In [14]:
print('confusion matrix : \n', cm)       
print(f'\nAccuracy score : {acc : 0.2%}')

confusion matrix : 
 [[451  49]
 [  0 500]]

Accuracy score :  95.10%
